framework = "Accessibility"
crate = "objc2-accessibility"
required-dependencies = ["objc2-foundation"]
macos = "11.0"
maccatalyst = "14.0"
ios = "14.0"
tvos = "14.0"
watchos = "7.0"
visionos = "1.0"

static.AXFeatureOverrideSessionErrorDomain.skipped = true
